// import request from '@/utils/request';

export async function fetchBlog() {
  return [
    {
      id: 1000592996,
      urlHandle: 'video',
      title: 'Video',
      tags: [
        'bao cao su',
        'durex',
        'shell',
        'bao cao su keo dai thoi gian',
        'review',
        'bao cao su siêu mỏng',
        'video',
        'youtube',
        'đông trùng hạ thảo',
        'phỏng vấn đường phố',
        'bao cao su sea horse',
        'bao cao su hongkong',
        'xuất tinh sớm',
        'Cải thiện chức năng sinh lý',
        'kéo dài thời gian quan hệ',
        'bao cao su nga',
        'kimono',
      ],
    },
    {
      id: 1000592995,
      urlHandle: 'chia-se-tu-van',
      title: 'Chia sẻ - Tư vấn',
      tags: [
        'Bao cao su Nhật',
        'Bao cao su Nhật Bản',
        'Bao cao su Sagami',
        'Bao cao su siêu mỏng',
        'Quan hệ tình dục.',
        'Số lượng bao cao su',
        'Bao cao su hộp 3 cái',
        'Bao cao su hộp 6 cái',
        'Bao cao su hộp 12 cái',
        'Bao cao su Durex',
        'Bao cao su Shell',
        'Bao cao su Innova',
        'Bao cao su Nakanishi',
        'Mang hai bao cao su',
        'Size bao cao su',
        'Bệnh lây nhiễm qua đường tình dục',
        'Khoái cảm',
        'Rách bao cao su',
        'Gel bôi trơn',
        'Có thai ngoài ý muốn',
        'Bao cao su Azodra',
        'Cách sử dụng bao cao su',
        'Sai lầm khi dùng bao cao su',
        'Loại bao cao su',
        'Bao cao su hương thơm',
        'Bao cao su gân',
        'Bao cao su gai',
        'Bao cao su gân gai',
        'Bao cao su  Sagami',
        'Bao cao su Sagami Type E',
        'Bao cao su Sagami Feel Up',
        'Bao cao su Sagami Exceed 2000',
        'Bao cao su Feel',
        'Cách dùng bao cao su',
        'Bao cao su Usupita Hi Grade',
        'Bao cao su Usupita Silky 0',
        '03',
        'Bao cao su Super Gold',
        'Cách đeo bao cao su',
        'Kích cỡ dương vật',
        'Bệnh nam khoa',
        'Bệnh xã hội',
        'bao cao su tốt',
        'Bao cao su Azodra 4 in 1',
        'Bao cao su Shell Seahorse',
        'Bao Cao Su Durex Performa',
        'Bao cao su Shell Performax',
        'Thuốc xịt dương vật',
        'Thuốc xịt chống xuất tinh sớm',
        'Xuất tinh sớm',
        'Yếu sinh lý',
        'Chai xịt Herbecaot',
        'Chai xịt Dynamo',
        'Chai xịt Stud',
        'Chai xịt Playboy',
        'Chai xịt Longtime',
        'Chai xịt Dynamo Delay',
        'Bao cao su gai mềm',
        'Bao cao su gân gai bi',
        'Bao cao su bi Storm',
        'Bao cao su Condom Muaisi',
        'Bao cao su Toshiro Long Shock 4in1',
        'Bao cao su Nhật Bản Usupita Hi Grade',
        'Bao cao su Malaysia Cá Ngựa.',
        'Nuốt tinh trùng',
        'HIV',
        'Bệnh lây nhiễm tình dục',
        'Quan hệ bằng miệng',
        'Oral sex',
        'Màn dạo đầu',
        'Cách dạo đầu cho nữ giới',
        'Cách dạo đầu cho nam giới',
        'sextoy',
        'Màn dạo đầu hoàn hảo',
        'Điểm G',
        'Kích thích cực khoái',
        'Kích thích điểm G',
        'Giảm ham muốn',
        'Suy giảm testosterone',
        'Sản phẩm hỗ trợ tăng cường sinh lý',
        'Sextoy.',
        'Tinh chất Hachimitsu',
        'Đông trùng hạ thảo.',
        'Đông trùng hạ thảo',
        'Giảm estrogen.',
        'Bệnh phụ khoa',
        'Viêm âm đạo',
        'U nang buồng trứng',
        'Ung thư cổ tử cung',
        'Giảm ham muốn sau sinh',
        'Khô âm đạo',
        'Suy giảm ham muốn',
        'Giảm ham muốn khi mang thai',
        'Quan hệ khi mang thai',
        'Thuốc tránh thai',
        'Bao cao su Shell Performax 6 in 1',
        'Bao cao su Innova đen',
        'Bao cao su Feel 4 in 1',
        'Rối loạn cương dương',
        'Viêm tuyến tiền liệt',
        'Sùi mào gà',
        'Giang mai',
        'Biểu hiện bệnh phụ khoa ở nữ giới',
        'Ngứa vùng kín',
        'Quan hệ hậu môn',
        'Anal sex',
        'Hướng dẫn vệ sinh vùng kín',
        'Vệ sinh vùng kín đúng cách sau quan hệ',
        'Quan hệ bằng miệng có thai',
        'Khô hạn âm đạo',
        'Tinh trùng yếu',
        'Chất lượng tinh trùng',
        'Sản phẩm hỗ trợ tình dục.',
        'Cải thiện chức năng sinh lý',
        'Tăng cường sinh lý',
        'Hachimitsu',
        'Đông Trùng Hạ Thảo',
        'Chất lượng tinh trùng yếu',
        'Yếu sinh lý.',
        'Quan hệ khi mang thai.',
        'Kích thước bao cao su',
        'Bao cao su gai Nhật',
        'Phòng tránh thai an toàn',
        'Bệnh tình dục',
        'Phòng ngừa bệnh tình dục',
        'Bao cao su Durex Invisible Extra Sensitive',
        'Thuốc tránh thai khẩn cấp',
        'Chữa yếu sinh lý',
        'Chống xuất tinh sớm',
        'Tăng cường testosterone',
        'Tập thể dục tăng testosterone',
        'Thuốc tránh thai hàng ngày',
        'Ăn gì để không mang thai',
        'Quan hệ khi mang thai 3 tháng đầu.',
        'Quan hệ bằng tay',
        'Handjob (HJ)',
        'Handjob (HJ).',
        'Virus Herpes',
        'Quan hệ an toàn',
        'Herpes miệng',
        'Herpes sinh dục',
        'Bị Herpes khi mang thai.',
        'Mùi hôi vùng kín',
        'Cách khử mùi hôi vùng kín',
        'Vệ sinh vùng kín.',
        'Cách khử mùi hôi vùng kín sau sinh',
        'Viêm nhiễm âm đạo',
        'Bệnh lây nhiễm qua đường quan hệ tình dục',
        'Gel bôi trơn gốc nước',
        'Cách sử dụng gel bôi trơn',
        'Gel bôi trơn hậu môn',
        'Quan hệ đồng giới',
        'Quan hệ hậu môn.',
        'Gel bôi trơn nóng ấm',
        'Gel bôi trơn mát lạnh',
        'Gel bôi trơn Warming',
        'Gel bôi trơn Cooling',
        'Gel bôi trơn Lexy Warming',
        'Gel bôi trơn Lexy Cooling',
        'Gel bôi trơn Durex Tingle',
        'Gel bôi trơn Durex Warming.',
        'Gel bôi trơn hương trái cây',
        'Gel bôi trơn Silk Touch Peach',
        'Gel bôi trơn Silk Touch Lemon',
        'Gel bôi trơn Silk Touch Apple',
        'Gel bôi trơn Hot Kiss Cherry',
        'Gel bôi trơn Love Kiss Dâu.',
        'Lãnh cảm ở phụ nữ',
        'Giảm ham muốn tình dục',
        'Điều trị xuất tinh sớm',
        'Chai xịt xuất tinh sớm',
        'Chai Xịt Dynamo Delay.',
        'Xịt xuất tinh',
        'Thuốc tăng sinh lý nam.',
        'Thuốc tăng cường sinh lý',
        'Kẹo tăng cường sinh lý',
        'Kẹo nhân sâm Xtreme',
        'Thuốc cường dương',
        'Kẹo nhân sâm S-Dream',
        'Chai Xịt Dynamo Delay',
        'Kẹo Xtreme',
        'Kẹo S-Dream',
        'Thuốc tăng cường sinh lý nam',
        'Viên nén con tê giác Mỹ Rhino 7 Platinum 5000',
        'Kẹo sâm Xtreme',
        'Thuốc Spanish Fly',
        'Thuốc Majegra',
        'Thuốc Azodra',
        'Thuốc Ngựa Thái',
        'Thuốc Japan Tengsu',
        'Hỗ trợ tình dục',
        'Quan hệ lần đầu.',
        'Quan hệ lần đầu',
        'Gel bôi trơn.',
        'Thủ dâm',
        'Ngày rụng trứng',
        'Cách tính ngày rụng trứng',
        'Phòng tránh thai',
        'Quan hệ tình dục',
        'Gel bôi trơn Durex Intense Orgasmic',
      ],
    },
    {
      id: 1000592994,
      urlHandle: 'tin-tuc-su-kien',
      title: 'Tin tức - sự kiện',
      tags: [
        'nhượng quyền thương hiệu Gunshop',
        'bán hàng cùng Gunshop',
        'nhượng quyền thương hiệu',
        'nhượng quyền gunshop',
        'bao cao su gunshop',
        'nhượng quyền cửa hàng',
        'bao cao su lâm đồng',
        'gunshop',
        'bao cao su long khánh',
        'bao cao su đồng nai',
        'cửa hàng nhượng quyền',
        'sexshop',
        'cửa hàng bao cao su gunshop',
        'gunshop Đà Lạt',
        'sex shop',
        'đặt hàng online',
        'gunshop.vn',
        'giao hàng nội thành',
        'khai trương giảm giá',
        'dụng cụ hỗ trợ tình dục',
        'condom',
        'sextoys',
        'áo mưa nhỏ',
        '295 Phan Đình Phùng',
        'vườn hoa đà lạt',
        'đà lạt trong màn sương',
        'svakom',
        'đồ chơi tình yêu',
        'đồ chơi tình dục',
        'sextoy svakom',
        'sextoy gunshop',
        'đồ chơi tình dục cho nam',
        'đồ chơi tình dục cho nữ',
        'baocaosu',
        'khuyến mãi',
        'sale khủng',
        'thu6khomau',
        'Thứ 6 khô máu',
        'khuyến mãi Gunshop',
        'thông tin khuyến mãi Gunshop',
        'tiếp thị liên kết',
        'quốc tế phụ nữ',
        'mùng 8 tháng 3',
        'bao cao su tân phú',
        'ham muốn tình dục',
        'ở nhà cùng người ấy',
        'giao hàng online',
        'giao hàng nhanh nhất',
        'giao hàng hỏa tốc',
        'shop bao cao su',
        'đặt hàng nhanh',
        'giao hàng trong 2 tiếng',
        'giao hàng nhanh',
        'chính sách giao hàng',
        'giao hàng trong 24 giờ',
        'nhượng quyền',
        'bcs',
        'valentine',
        'ưu đãi',
        'bao cao su cần thơ',
        'bao cao su vũng tàu',
        'gunshop vũng tàu',
        'cửa hàng bao cao su vũng tàu',
        'cửa hàng bao cao su',
        'nhương quyền cửa hàng',
        'nhượng quyền cửa hàng gunshop',
        'nhượng quyền thương hiệu gunshop',
        'black friday',
        'khuyến mãi bao cao su',
        'gunshop khuyến mãi',
        'giảm giá',
        'bao cao su gò vấp',
        'gò vấp',
        'bao cao su phan văn trị',
        'gunshop gò vấp',
        'bao cao su tân bình',
        'gunshop tân bình',
        'gunshop lâm đồng',
        'gunshop phi nôm',
        'cửa hàng bao cao su lâm đồng',
        'bao cao su đức trọng',
        'Đón Trung Thu cùng Gunshop',
        'gunshop quận 7',
        'bao cao su quận 7',
        'shop bao cao su quận 7',
        'vòng loại worldcup',
        'đội tuyển VN',
        'đi cùng đội tuyển VN',
        'Đón lễ tại Gunshop',
        'khuyễn mãi 2-9',
        'quốc khánh',
        'Cần Thơ đón cửa hàng Gunshop thứ 6',
        'Chào đón cửa hàng Gunshop thứ 6 tại Cần Thơ',
        'combo vàng',
        'combo vàng 400 gunshop',
        'flashsale',
        'tất tay cuối tháng',
        'gunshop kahi trương',
        'gunshop đà nẵng',
        'gunshop nguyễn oanh',
        'mua bao cao su ở đâu',
        'bao cao su quận 3',
        'mua bao cao su ở quận 3',
        'chỗ nào quận 3 bán bao cao su',
        'bao cao su tốt nhất ở quận 3',
        'địa chỉ bán bao cao su ở quận 3',
        'quận 3 có địa chỉ nào bán bao cao su',
        'Cần vốn tối thiểu bao nhiêu để có thể nhượng quyền?',
        'chi phí nhượng quyền thương hiệu',
        'phí nhượng quyền',
        'hỗ trợ vốn',
        'Lợi ích khi nhận nhượng quyền cửa hàng Gunshop',
        'Công ty sẽ hỗ trợ những gì cho người nhận nhượng quyền?',
        'Công ty sẽ hỗ trợ những gì?',
        'Bản thân người đi nhượng quyền sẽ làm gì',
        'Bản thân người đi nhượng quyền cần chuẩn bị những gì',
        'kẹo sâm Hamer',
        'gel lexy',
        'đôn dên',
        'đôn dương vật',
        'bao tăng kích thước',
        'Gunshop có gì mới',
        'Bao cao su Sagami Exceed',
        'Gel bôi trơn kích thích khoái cảm Provocative',
        'Máy rung kích thích đầu ti',
        'Vòng rung 10 chế độ Sinmis',
        'Dương vật giả cao cấp 10 chế độ Lovetoy',
        'Cây Nhật xoay 360 độ Enjoy YourSelf',
        'Dương vật giả rung hình trái chuối',
        'Lưỡi rung Pretty Love',
        'Lưỡi rung đeo ngón tay',
        'Bộ dụng cụ roi da',
        'Thông báo nghỉ lễ Giỗ tổ Hùng Vương',
        'gunshop nghỉ lễ',
        'gunshop quận 6',
        'khai trương gunshop quận 6',
        'Chào đón Gunshop thứ hai tại Tân Phú Tưng bừng khai trương',
        '300 bình long',
        'gunshop bình long',
        'gunshop tân phú',
        'giao hàng toàn quốc',
        'tâm sự buổi đêm',
        'mua hàng online',
        'hội FA',
        'freeship',
        'freeship hóa đơn',
        'sự thăng hoa',
      ],
    },
    {
      id: 1000568812,
      urlHandle: 'giai-tri',
      title: 'Giải trí',
      tags: [
        '6 bí kíp chụp ảnh Flatlay siêu chất',
        'chụp ảnh flatlay',
        'flatlay',
        'cách chụp ảnh flatlay đẹp',
        'giải trí',
        'các tips trang điểm',
        'làm đẹp',
      ],
    },
    {
      id: 1000381989,
      urlHandle: 'phuong-thuc-van-chuyen',
      title: 'Phương thức vận chuyển',
      tags: [
        'giao hàng kín đáo',
        'giao hàng che tên sản phẩm',
        'giao hàng bí mật',
        'giao hàng online',
        'giao hàng nhanh',
        'gunshop',
        'mua hàng online',
        'thời gian giao hàng',
        'bao cao su',
        'gel bôi trơn',
        'sextoys',
        'Gunshop Giao Hàng Trong Bao Lâu?',
        'Cước phí vận chuyển được tính như thế nào',
      ],
    },
    {
      id: 1000380296,
      urlHandle: 'nhuong-quyen-thuong-hieu',
      title: 'Nhượng Quyền Thương Hiệu',
      tags: [
        'nhượng quyền thương hiệu',
        'Cần vốn tối thiểu bao nhiêu để có thể nhượng quyền?',
        'Gunshop',
        'chi phí nhượng quyền thương hiệu',
        'phí nhượng quyền',
        'hỗ trợ vốn',
        'Lợi ích khi nhận nhượng quyền cửa hàng Gunshop',
        'Công ty sẽ hỗ trợ những gì cho người nhận nhượng quyền?',
        'Công ty sẽ hỗ trợ những gì?',
        'Bản thân người đi nhượng quyền sẽ làm gì',
        'Bản thân người đi nhượng quyền cần chuẩn bị những gì',
      ],
    },
    {
      id: 1000379014,
      urlHandle: 'chuyen-hoa-mi',
      title: 'Chuyện Họa Mi',
      tags: [
        'tóc nam đẹp',
        'tóc nam phù hợp với khuôn mặt',
        'wax vuốt tóc',
        'kiểu tóc đẹp cho nam',
        'các kiểu tóc nam đẹp',
        'các kiểu gương mặt nam giới',
        'các mẫu tóc đẹp',
        'kiểu tóc nam cho mặt tròn',
        'tóc nam cho mặt vuông',
        'tóc nam cho mặt trái xoan',
        'tóc nam cho mặt tam giác',
        'tóc nam cho mặt hình thoi',
      ],
    },
    {
      id: 1000373764,
      urlHandle: 'dat-hang-tai-gunshop',
      title: 'Đặt hàng tại Gunshop',
      tags: [
        'giao hàng kín đáo',
        'giao hàng che tên sản phẩm',
        'giao hàng bí mật',
        'mua sextoys online',
        'bao cao su',
        'gel bôi trơn',
        'sextoys',
        'giao hàng nhanh kín đáo',
        'khoái lạc',
        'mua hàng online',
        'gunshop',
        'dương vật giả',
        'dương vật giả cao cấp',
        'giao hàng tận tay',
        'đặt h',
        'àng online',
      ],
    },
    {
      id: 1000372773,
      urlHandle: 'news',
      title: 'Thông tin khuyến mãi',
      tags: [
        'gunshop.vn',
        'ham muốn tình dục',
        'ở nhà cùng người ấy',
        'bao cao su',
        'giao hàng online',
        'giao hàng nhanh nhất',
        'giao hàng hỏa tốc',
        'shop bao cao su',
        'giao hàng toàn quốc',
        'tâm sự buổi đêm',
        'gunshop',
        'mua hàng online',
        'hội FA',
        'đặt hàng nhanh',
        'giao hàng trong 2 tiếng',
        'giao hàng nhanh',
        'chính sách giao hàng',
        'giao hàng trong 24 giờ',
        'freeship',
        'freeship hóa đơn',
        'sự thăng hoa',
        'dụng cụ hỗ trợ tình dục',
        'gunshop Đà Lạt',
        'sex shop',
        'đặt hàng online',
        'giao hàng nội thành',
        'khai trương giảm giá',
        'condom',
        'sextoys',
        'áo mưa nhỏ',
        '295 Phan Đình Phùng',
        'vườn hoa đà lạt',
        'đà lạt trong màn sương',
        'gunshop quận 6',
        'khai trương gunshop quận 6',
        'Chào đón Gunshop thứ hai tại Tân Phú',
        'Tưng bừng khai trương',
        '300 Bình Long',
        'Phú Thọ Hòa',
        'Tân Phú',
        'Gunshop Bình Long',
        'Gunshop Tân Phú',
        'Chào đón Gunshop thứ hai tại Tân Phú Tưng bừng khai trương',
        '300 bình long',
        'gunshop bình long',
        'gunshop tân phú',
        'cửa hàng gunshop',
        'Tưng bừng đón chào Gunshop Nguyễn Đình Chiểu',
        'Gunshop',
        'gel bôi trơn',
        'bao cao su shop',
        'gunshop đà lạt',
        'bao cao su đà lạt',
        'Thông báo nghỉ lễ Giỗ tổ Hùng Vương',
        'gunshop nghỉ lễ',
        'thu6khomau',
        'Thứ 6 khô máu',
        'khuyến mãi Gunshop',
        'thông tin khuyến mãi Gunshop',
        'Gunshop có gì mới',
        'Bao cao su Sagami Exceed',
        'Gel bôi trơn kích thích khoái cảm Provocative',
        'Máy rung kích thích đầu ti',
        'Vòng rung 10 chế độ Sinmis',
        'Dương vật giả cao cấp 10 chế độ Lovetoy',
        'Cây Nhật xoay 360 độ Enjoy YourSelf',
        'Dương vật giả rung hình trái chuối',
        'Lưỡi rung Pretty Love',
        'Lưỡi rung đeo ngón tay',
        'Bộ dụng cụ roi da',
        'khuyến mãi',
        'kẹo sâm Hamer',
        'gel lexy',
        'đôn dên',
        'đôn dương vật',
        'bao tăng kích thước',
        'bán hàng cùng Gunshop',
        'nhượng quyền thương hiệu Gunshop',
        'nhượng quyền thương hiệu',
        'nhượng quyền gunshop',
      ],
    },
  ].map((item) => ({ ...item, key: item.id }));
}
